function summary = exportNr5gTemplate(out_json_path, varargin)
%EXPORTNR5GTEMPLATE Export a narrow NR resource-grid template for Python parity.

    defaults = struct( ...
        'gridSize', 50, ...
        'subCarrierSpacing_kHz', 15, ...
        'centerFreq_Hz', 3.8e9, ...
        'bandwidth_MHz', 10, ...
        'numSubframes', 1, ...
        'cyclicPrefix', "Normal", ...
        'modulation', "QPSK", ...
        'waveformProfile', "control");
    [opts, ~] = parseOptions(defaults, varargin{:});

    [~, info] = nr5gDl( ...
        opts.gridSize, ...
        opts.subCarrierSpacing_kHz, ...
        opts.centerFreq_Hz, ...
        opts.bandwidth_MHz, ...
        opts.numSubframes, ...
        char(opts.cyclicPrefix), ...
        char(opts.modulation), ...
        char(opts.waveformProfile));

    grid = info.ResourceGrids(1).ResourceGridBWP;
    nonzero = find(abs(grid) > 0);
    values = grid(nonzero);

    nfft = 3200;
    symbol_sample_rate_hz = 48e6;
    cp_lengths = [250, 225, 225, 225, 225, 225, 225, 250, 225, 225, 225, 225, 225, 225];
    symbol_lengths = [3450, 3425, 3425, 3425, 3425, 3425, 3425, 3450, 3425, 3425, 3425, 3425, 3425, 3425];
    offsets = cumsum(symbol_lengths) - nfft;
    symbol_phases = -2.0 * pi * double(opts.centerFreq_Hz) * offsets / symbol_sample_rate_hz;

    template = struct( ...
        'grid_rows', size(grid, 1), ...
        'grid_cols', size(grid, 2), ...
        'grid_indices', reshape(nonzero, 1, []), ...
        'grid_symbols_real', reshape(real(values), 1, []), ...
        'grid_symbols_imag', reshape(imag(values), 1, []), ...
        'nfft', nfft, ...
        'sample_rate', 40e6, ...
        'cp_lengths', cp_lengths, ...
        'symbol_lengths', symbol_lengths, ...
        'symbol_phases', symbol_phases, ...
        'grid_size', opts.gridSize, ...
        'center_freq_hz', double(opts.centerFreq_Hz), ...
        'channel_bandwidth_hz', double(opts.bandwidth_MHz) * 1e6, ...
        'modulation', char(opts.modulation), ...
        'waveform_profile', char(opts.waveformProfile));

    fid = fopen(out_json_path, 'w');
    assert(fid ~= -1, 'exportNr5gTemplate:OpenFailed', 'Unable to open output file: %s', out_json_path);
    cleanup = onCleanup(@() fclose(fid));
    fwrite(fid, jsonencode(template, 'PrettyPrint', true), 'char');
    fwrite(fid, newline, 'char');

    summary = struct( ...
        'outputPath', string(out_json_path), ...
        'nonzeroCount', numel(nonzero), ...
        'gridRows', size(grid, 1), ...
        'gridCols', size(grid, 2), ...
        'modulation', string(opts.modulation), ...
        'waveformProfile', string(opts.waveformProfile));

    fprintf('%s\n', jsonencode(summary, 'PrettyPrint', true));
end
