function summary = exportLteDlFddMatrix(expanded_manifest_path, out_dir)
%EXPORTLTEDLFDDMATRIX Export an LTE DL FDD oracle matrix from an expanded manifest.

    manifest = jsondecode(fileread(char(expanded_manifest_path)));
    if nargin < 2 || strlength(string(out_dir)) == 0
        out_dir = manifest.profile_dir;
    end
    out_dir = string(out_dir);
    if ~isfolder(out_dir)
        mkdir(out_dir);
    end

    profiles = manifest.profiles;
    if isstruct(profiles)
        profiles = num2cell(profiles);
    end

    exported = cell(numel(profiles), 1);
    for idx = 1:numel(profiles)
        profile = profiles{idx};
        args = profile.match;

        [~, info] = lteDlFddWaveform( ...
            'centerFreq_Hz', double(args.centerFreq_Hz), ...
            'NDLRB', double(args.NDLRB), ...
            'TotSubframes', double(args.TotSubframes), ...
            'CP', char(args.CP), ...
            'modulation', char(args.modulation));

        message_path = fullfile(char(out_dir), char(profile.message_filename));
        fid = fopen(message_path, 'w');
        assert(fid ~= -1, 'exportLteDlFddMatrix:OpenFailed', 'Unable to open output file: %s', message_path);
        cleanup = onCleanup(@() fclose(fid));
        fwrite(fid, jsonencode(struct('message_bits', reshape(info.message, 1, [])), 'PrettyPrint', true), 'char');
        fwrite(fid, newline, 'char');
        clear cleanup;

        template_path = fullfile(char(out_dir), char(profile.template_filename));
        exportLteDlFddTemplate( ...
            template_path, ...
            'centerFreq_Hz', double(args.centerFreq_Hz), ...
            'NDLRB', double(args.NDLRB), ...
            'TotSubframes', double(args.TotSubframes), ...
            'CP', char(args.CP), ...
            'modulation', char(args.modulation), ...
            'messagePath', message_path);

        exported{idx} = struct( ...
            'instance_preset', string(profile.instance_preset), ...
            'template_filename', string(profile.template_filename), ...
            'message_filename', string(profile.message_filename), ...
            'sample_rate_hz', double(args.transmissionRate_Hz), ...
            'bandwidth_hz', double(args.bandwidth_Hz));
    end

    summary = struct( ...
        'expanded_manifest_path', string(expanded_manifest_path), ...
        'out_dir', out_dir, ...
        'profile_count', numel(profiles), ...
        'profiles', {exported});
    fprintf('%s\n', jsonencode(summary, 'PrettyPrint', true));
end
