function summary = exportLteDlFddTemplate(out_json_path, varargin)
%EXPORTLTEDLFDDTEMPLATE Export one narrow LTE waveform template for Python parity.

    [dataIQ, info] = lteDlFddWaveform(varargin{:});
    payload = struct( ...
        'samples_real', reshape(real(dataIQ), 1, []), ...
        'samples_imag', reshape(imag(dataIQ), 1, []), ...
        'sample_rate_hz', double(info.transmissionRate_Hz), ...
        'bandwidth_hz', double(info.bandwidth_Hz), ...
        'center_freq_hz', double(info.centerFreq_Hz), ...
        'ndlrb', double(info.cfgLTE.NDLRB), ...
        'tot_subframes', double(info.cfgLTE.TotSubframes), ...
        'cyclic_prefix', char(info.cfgLTE.CyclicPrefix), ...
        'modulation', char(info.modulation));

    fid = fopen(out_json_path, 'w');
    assert(fid ~= -1, 'exportLteDlFddTemplate:OpenFailed', 'Unable to open output file: %s', out_json_path);
    cleanup = onCleanup(@() fclose(fid));
    fwrite(fid, jsonencode(payload, 'PrettyPrint', true), 'char');
    fwrite(fid, newline, 'char');

    summary = struct( ...
        'outputPath', string(out_json_path), ...
        'sampleCount', numel(dataIQ), ...
        'sampleRate_Hz', double(info.transmissionRate_Hz), ...
        'bandwidth_Hz', double(info.bandwidth_Hz), ...
        'modulation', string(info.modulation));
    fprintf('%s\n', jsonencode(summary, 'PrettyPrint', true));
end
