function [nr_dl_waveform, info] = nr5gDl(grid_size, sub_car_sp, fc, nr_bw, n_sf, CP, pdsch_mod)
%NR5GDL Create a narrow NR downlink waveform for local oracle comparison.

    carrier = nrSCSCarrierConfig( ...
        'SubcarrierSpacing', sub_car_sp, ...
        'NSizeGrid', grid_size, ...
        'NStartGrid', 0);

    bwp = nrWavegenBWPConfig( ...
        'NStartBWP', carrier.NStartGrid, ...
        'CyclicPrefix', CP, ...
        'NSizeBWP', 50);

    crst = {nrCORESETConfig};
    crst{1}.FrequencyResources = ones(1, 6);
    crst{1}.Duration = 3;
    crst{1}.REGBundleSize = 3;

    ssb = nrWavegenSSBurstConfig( ...
        'Enable', 0, ...
        'Power', 3, ...
        'BlockPattern', 'Case A', ...
        'TransmittedBlocks', [1 1 1 1], ...
        'Period', 5);

    pdcch = {nrWavegenPDCCHConfig( ...
        'Enable', 1, ...
        'BandwidthPartID', 1, ...
        'Power', 1.1, ...
        'Coding', 1, ...
        'SearchSpaceID', 1, ...
        'Period', 5, ...
        'AggregationLevel', 8, ...
        'DataBlockSize', 20, ...
        'DataSource', 'PN9')};

    pdsch = {nrWavegenPDSCHConfig};
    pdsch{1}.Enable = 0;
    pdsch{1}.Modulation = pdsch_mod;

    nr_dl_cfg = nrDLCarrierConfig( ...
        'Label', 'DL_1', ...
        'FrequencyRange', 'FR1', ...
        'ChannelBandwidth', nr_bw, ...
        'NumSubframes', n_sf, ...
        'SampleRate', 40e6, ...
        'CarrierFrequency', fc, ...
        'SSBurst', ssb, ...
        'SCSCarriers', {carrier}, ...
        'BandwidthParts', {bwp}, ...
        'CORESET', crst, ...
        'PDCCH', pdcch, ...
        'PDSCH', pdsch);

    [nr_dl_waveform, info] = nrWaveformGenerator(nr_dl_cfg);
end
