function [nr_dl_waveform, info] = nr5gDl(grid_size, sub_car_sp, fc, nr_bw, n_sf, CP, pdsch_mod, waveform_profile, test_vector_path)
%NR5GDL Create a narrow NR downlink waveform for local oracle comparison.

    if nargin < 8 || isempty(waveform_profile)
        waveform_profile = 'control';
    end
    if nargin < 9
        test_vector_path = '';
    end
    use_pdsch = strcmpi(waveform_profile, 'pdsch');
    payload_bits = [];
    if strlength(string(test_vector_path)) > 0
        raw = jsondecode(fileread(char(test_vector_path)));
        if isfield(raw, 'payload') && isfield(raw.payload, 'message_bits')
            payload_bits = logical(raw.payload.message_bits(:));
        end
    end

    carrier = nrSCSCarrierConfig( ...
        'SubcarrierSpacing', sub_car_sp, ...
        'NSizeGrid', grid_size, ...
        'NStartGrid', 0);

    bwp = nrWavegenBWPConfig( ...
        'NStartBWP', carrier.NStartGrid, ...
        'CyclicPrefix', CP, ...
        'NSizeBWP', grid_size);

    crst = {nrCORESETConfig};
    n_coreset_groups = max(1, min(6, floor(grid_size / 6)));
    crst{1}.FrequencyResources = ones(1, n_coreset_groups);
    crst{1}.Duration = 3;
    crst{1}.REGBundleSize = 3;
    n_coreset_cces = n_coreset_groups * crst{1}.Duration;

    search_spaces = {nrSearchSpaceConfig};
    search_spaces{1}.SearchSpaceID = 1;
    search_spaces{1}.CORESETID = 1;
    search_spaces{1}.SearchSpaceType = 'ue';
    search_spaces{1}.StartSymbolWithinSlot = 0;
    search_spaces{1}.SlotPeriodAndOffset = [1 0];
    search_spaces{1}.Duration = 1;
    search_spaces{1}.NumCandidates = min(8, floor(n_coreset_cces ./ [1 2 4 8 16]));

    ssb = nrWavegenSSBurstConfig( ...
        'Enable', 0, ...
        'Power', 3, ...
        'BlockPattern', 'Case A', ...
        'TransmittedBlocks', [1 1 1 1], ...
        'Period', 5);

    pdcch = {nrWavegenPDCCHConfig( ...
        'Enable', ~use_pdsch, ...
        'BandwidthPartID', 1, ...
        'Power', 1.1, ...
        'Coding', 1, ...
        'SearchSpaceID', 1, ...
        'Period', 5, ...
        'AggregationLevel', 2^floor(log2(max(1, n_coreset_cces))), ...
        'DataBlockSize', 20, ...
        'DataSource', 'PN9')};
    if ~isempty(payload_bits) && ~use_pdsch
        pdcch{1}.DataSource = double(payload_bits(:)).';
    end

    pdsch = {nrWavegenPDSCHConfig};
    pdsch{1}.Enable = use_pdsch;
    pdsch{1}.Modulation = pdsch_mod;
    if use_pdsch
        pdsch{1}.PRBSet = 0:(grid_size - 1);
        if ~isempty(payload_bits)
            pdsch{1}.DataSource = double(payload_bits(:)).';
        end
    end

    nr_dl_cfg = nrDLCarrierConfig( ...
        'Label', 'DL_1', ...
        'FrequencyRange', 'FR1', ...
        'ChannelBandwidth', nr_bw, ...
        'NumSubframes', n_sf, ...
        'SampleRate', 40e6, ...
        'CarrierFrequency', fc, ...
        'SSBurst', ssb, ...
        'SCSCarriers', {carrier}, ...
        'BandwidthParts', {bwp}, ...
        'CORESET', crst, ...
        'SearchSpaces', search_spaces, ...
        'PDCCH', pdcch, ...
        'PDSCH', pdsch);

    [nr_dl_waveform, info] = nrWaveformGenerator(nr_dl_cfg);
end
