classdef DummySignal < atomic.Signal
    properties (SetAccess = private)
        transmissionTotTime (1,1) double = 0.004;
    end

    methods
        function this = DummySignal(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'bandwidth_Hz', 1e6, ...
                'txPower_db', 0, ...
                'transmissionTotTime', 0.004);

            [opts, ~] = parseOptions(defaults, varargin{:});

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.bandwidth_Hz, ...
                'bandwidth_Hz', opts.bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.unknown, ...
                'modulation', report.Modulation.unknown);

            this.transmissionTotTime = opts.transmissionTotTime;
        end

        function dataIQ = generateTransmission(this)
            dataIQ = zeros(round(this.transmissionRate_Hz * this.transmissionTotTime), 1);
        end
    end
end
