classdef Gfsk < atomic.Signal
    properties (SetAccess = private)
        samplesPerSymbol (1,1) double {mustBePositive, mustBeInteger} = 8;
        modOrder (1,1) double {mustBePositive, mustBeInteger} = 2;
        nDataSymb (1,1) double {mustBePositive, mustBeInteger} = 100;
        bandwidthTimeProduct (1,1) double {mustBePositive} = 0.35;
        modulationIndex (1,1) double {mustBePositive} = 0.5;
    end

    methods
        function this = Gfsk(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'transmissionRate_Hz', 250e3, ...
                'txPower_db', 0, ...
                'samplesPerSymbol', 8, ...
                'modOrder', 2, ...
                'bandwidthTimeProduct', 0.35, ...
                'modulationIndex', 0.5, ...
                'transmissionTotTime', 0.004, ...
                'bandwidth_Hz', nan);

            [opts, ~] = parseOptions(defaults, varargin{:});
            assert(mod(log2(opts.modOrder), 1) == 0, 'modOrder must be a power of 2');

            bandwidth_Hz = opts.bandwidth_Hz;
            if isnan(bandwidth_Hz)
                bandwidth_Hz = 2 * opts.transmissionRate_Hz;
            end

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'bandwidth_Hz', bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.single_carrier, ...
                'modulation', report.Modulation.gfsk);

            this.samplesPerSymbol = opts.samplesPerSymbol;
            this.modOrder = opts.modOrder;
            this.bandwidthTimeProduct = opts.bandwidthTimeProduct;
            this.modulationIndex = opts.modulationIndex;
            this.nDataSymb = max(1, round(opts.transmissionTotTime * opts.transmissionRate_Hz));
            this.transmissionRate_Hz = this.transmissionRate_Hz * this.samplesPerSymbol;
        end

        function dataIQ = generateTransmission(this)
            x = randi([0 this.modOrder - 1], this.nDataSymb, 1);
            modObj = comm.CPMModulator( ...
                'ModulationOrder', this.modOrder, ...
                'FrequencyPulse', 'Gaussian', ...
                'BandwidthTimeProduct', this.bandwidthTimeProduct, ...
                'ModulationIndex', this.modulationIndex, ...
                'SamplesPerSymbol', this.samplesPerSymbol);
            meanOffset = mean(0:this.modOrder - 1);
            dataIQ = modObj(2 * (x - meanOffset));
        end

        function regenerateWithRandomParams(this)
            supportedOrders = [2, 4, 8];
            this.modOrder = supportedOrders(randi(numel(supportedOrders)));
            this.nDataSymb = randi([64 512]);
        end
    end
end
