classdef Gmsk < atomic.Signal
    properties (SetAccess = private)
        samplesPerSymbol (1,1) double {mustBePositive, mustBeInteger} = 8;
        pulseLength (1,1) double {mustBePositive, mustBeInteger} = 4;
        nBits (1,1) double {mustBePositive, mustBeInteger} = 100;
        bandwidthTimeProduct (1,1) double {mustBePositive} = 0.35;
    end

    methods
        function this = Gmsk(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'transmissionRate_Hz', 250e3, ...
                'txPower_db', 0, ...
                'samplesPerSymbol', 8, ...
                'pulseLength', 4, ...
                'bandwidthTimeProduct', 0.35, ...
                'transmissionTotTime', 0.004, ...
                'bandwidth_Hz', nan);

            [opts, ~] = parseOptions(defaults, varargin{:});

            bandwidth_Hz = opts.bandwidth_Hz;
            if isnan(bandwidth_Hz)
                bandwidth_Hz = 1.5 * opts.transmissionRate_Hz;
            end

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'bandwidth_Hz', bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.single_carrier, ...
                'modulation', report.Modulation.gmsk);

            this.samplesPerSymbol = opts.samplesPerSymbol;
            this.pulseLength = opts.pulseLength;
            this.bandwidthTimeProduct = opts.bandwidthTimeProduct;
            this.nBits = max(1, round(opts.transmissionTotTime * opts.transmissionRate_Hz));
            this.transmissionRate_Hz = this.transmissionRate_Hz * this.samplesPerSymbol;
        end

        function dataIQ = generateTransmission(this)
            bits = randi([0 1], this.nBits, 1);
            modObj = comm.GMSKModulator( ...
                'BitInput', true, ...
                'BandwidthTimeProduct', this.bandwidthTimeProduct, ...
                'PulseLength', this.pulseLength, ...
                'SamplesPerSymbol', this.samplesPerSymbol);
            dataIQ = modObj(bits);
        end

        function regenerateWithRandomParams(this)
            this.nBits = randi([128 1024]);
        end
    end
end
