classdef LTE_DL_FDD < atomic.Signal
    properties (SetAccess = private)
        nPacket (1,1) double = 1
        idleTime (1,1) double = 0
        TotSubframes (1,1) double = 1
        message = []
        messagePath string = ""
        NDLRB (1,1) double = 6
        CP string = "Normal"
        modulation string = "QPSK"
    end

    methods
        function this = LTE_DL_FDD(varargin)
            defaults = struct( ...
                'trafficType', atomic.Traffic("periodic", "transmissionPerSec", 1), ...
                'centerFreq_Hz', 763e6, ...
                'txPower_db', -68, ...
                'nPacket', 1, ...
                'idleTime', 0, ...
                'TotSubframes', 1, ...
                'message', [], ...
                'messagePath', "", ...
                'NDLRB', 6, ...
                'CP', "Normal", ...
                'modulation', "QPSK");

            [opts, ~] = parseOptions(defaults, varargin{:});
            [bandwidth_Hz, transmissionRate_Hz] = lteDlFddPresetRates(opts.NDLRB);

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'bandwidth_Hz', bandwidth_Hz, ...
                'transmissionRate_Hz', transmissionRate_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.cellular, ...
                'modality', report.Modality.multi_carrier, ...
                'modulation', report.Modulation.ofdm);

            this.nPacket = opts.nPacket;
            this.idleTime = opts.idleTime;
            this.TotSubframes = opts.TotSubframes;
            this.message = opts.message;
            this.messagePath = string(opts.messagePath);
            this.NDLRB = opts.NDLRB;
            this.CP = string(opts.CP);
            this.modulation = string(opts.modulation);
        end

        function dataIQ = generateTransmission(this)
            dataIQ = lteDlFddWaveform( ...
                'centerFreq_Hz', this.centerFreq_Hz, ...
                'nPacket', this.nPacket, ...
                'idleTime', this.idleTime, ...
                'TotSubframes', this.TotSubframes, ...
                'message', this.message, ...
                'messagePath', char(this.messagePath), ...
                'NDLRB', this.NDLRB, ...
                'CP', char(this.CP), ...
                'modulation', char(this.modulation));
        end
    end
end
