classdef Msk < atomic.Signal
    properties (SetAccess = private)
        samplesPerSymbol (1,1) double {mustBePositive, mustBeInteger} = 8;
        modOrder (1,1) double {mustBePositive, mustBeInteger} = 2;
        nDataSymb (1,1) double {mustBePositive, mustBeInteger} = 100;
    end

    methods
        function this = Msk(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'transmissionRate_Hz', 250e3, ...
                'txPower_db', 0, ...
                'samplesPerSymbol', 8, ...
                'modOrder', 2, ...
                'transmissionTotTime', 0.004, ...
                'bandwidth_Hz', nan);

            [opts, ~] = parseOptions(defaults, varargin{:});
            bandwidth_Hz = opts.bandwidth_Hz;
            if isnan(bandwidth_Hz)
                bandwidth_Hz = 1.5 * opts.transmissionRate_Hz;
            end

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'bandwidth_Hz', bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.single_carrier, ...
                'modulation', report.Modulation.msk);

            this.samplesPerSymbol = opts.samplesPerSymbol;
            this.modOrder = opts.modOrder;
            this.nDataSymb = max(1, round(opts.transmissionTotTime * opts.transmissionRate_Hz));
            this.transmissionRate_Hz = this.transmissionRate_Hz * this.samplesPerSymbol;
        end

        function dataIQ = generateTransmission(this)
            x = randi([0 this.modOrder - 1], this.nDataSymb, 1);
            dataIQ = mskmod(x, this.samplesPerSymbol);
        end

        function regenerateWithRandomParams(this)
            this.nDataSymb = randi([64 512]);
        end
    end
end
