classdef nr5g < atomic.Signal
    %NR5G Narrow NR downlink atomic used as the local MATLAB oracle.

    properties (SetAccess = private)
        gridSize (1,1) double = 50
        subCarrierSpacing_kHz (1,1) double = 15
        numSubframes (1,1) double = 1
        cyclicPrefix string = "Normal"
        modulation string = "QPSK"
        waveformProfile string = "control"
        channelBandwidth_MHz (1,1) double = 10
    end

    methods
        function this = nr5g(varargin)
            defaults = struct( ...
                'trafficType', atomic.Traffic("periodic", "transmissionPerSec", 1), ...
                'centerFreq_Hz', 3.8e9, ...
                'txPower_db', -68, ...
                'gridSize', 50, ...
                'subCarrierSpacing_kHz', 15, ...
                'numSubframes', 1, ...
                'cyclicPrefix', "Normal", ...
                'modulation', "QPSK", ...
                'waveformProfile', "control", ...
                'bandwidth_Hz', 10e6, ...
                'transmissionRate_Hz', 40e6);

            [opts, ~] = parseOptions(defaults, varargin{:});
            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'bandwidth_Hz', opts.bandwidth_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.cellular, ...
                'modality', report.Modality.multi_carrier, ...
                'modulation', report.Modulation.ofdm);

            this.gridSize = opts.gridSize;
            this.subCarrierSpacing_kHz = opts.subCarrierSpacing_kHz;
            this.numSubframes = opts.numSubframes;
            this.cyclicPrefix = string(opts.cyclicPrefix);
            this.modulation = string(opts.modulation);
            this.waveformProfile = string(opts.waveformProfile);
            this.channelBandwidth_MHz = opts.bandwidth_Hz / 1e6;
        end

        function dataIQ = generateTransmission(this)
            dataIQ = nr5gDl( ...
                this.gridSize, ...
                this.subCarrierSpacing_kHz, ...
                this.centerFreq_Hz, ...
                this.channelBandwidth_MHz, ...
                this.numSubframes, ...
                char(this.cyclicPrefix), ...
                char(this.modulation), ...
                char(this.waveformProfile));
        end
    end
end
