classdef RandomSymbol < atomic.Signal
    properties (SetAccess = private)
        samplesPerSymbol (1,1) double {mustBePositive, mustBeInteger} = 4;
        modOrder (1,1) double {mustBePositive, mustBeInteger} = 4;
        nDataSymb (1,1) double {mustBePositive, mustBeInteger} = 100;
    end

    methods
        function this = RandomSymbol(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'transmissionRate_Hz', 1e6, ...
                'bandwidth_Hz', 1e6, ...
                'txPower_db', 0, ...
                'samplesPerSymbol', 4, ...
                'modOrder', 4, ...
                'transmissionTotTime', 0.004);

            [opts, ~] = parseOptions(defaults, varargin{:});

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'bandwidth_Hz', opts.bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.single_carrier, ...
                'modulation', report.Modulation.unknown);

            this.samplesPerSymbol = opts.samplesPerSymbol;
            this.modOrder = opts.modOrder;
            this.nDataSymb = max(1, round(opts.transmissionTotTime * opts.transmissionRate_Hz));
            this.transmissionRate_Hz = this.transmissionRate_Hz * this.samplesPerSymbol;
        end

        function dataIQ = generateTransmission(this)
            phases = randi([0 this.modOrder - 1], this.nDataSymb, 1);
            symbols = exp(2j * pi * phases / this.modOrder);
            dataIQ = repelem(symbols, this.samplesPerSymbol);
        end

        function regenerateWithRandomParams(this)
            supportedOrders = [2, 4, 8, 16];
            this.modOrder = supportedOrders(randi(numel(supportedOrders)));
            this.nDataSymb = randi([64 512]);
        end
    end
end
