classdef Sine < atomic.Signal
    properties (SetAccess = private)
        toneOffset_Hz (1,1) double = 100e3;
        transmissionTotTime (1,1) double = 0.004;
    end

    methods
        function this = Sine(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'transmissionRate_Hz', 1e6, ...
                'bandwidth_Hz', 200e3, ...
                'txPower_db', 0, ...
                'toneOffset_Hz', 100e3, ...
                'transmissionTotTime', 0.004);

            [opts, ~] = parseOptions(defaults, varargin{:});

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'bandwidth_Hz', opts.bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.single_carrier, ...
                'modulation', report.Modulation.no_answer);

            this.toneOffset_Hz = opts.toneOffset_Hz;
            this.transmissionTotTime = opts.transmissionTotTime;
        end

        function dataIQ = generateTransmission(this)
            nSamples = max(1, round(this.transmissionTotTime * this.transmissionRate_Hz));
            n = (0:nSamples - 1).';
            dataIQ = exp(2j * pi * this.toneOffset_Hz / this.transmissionRate_Hz .* n);
        end
    end
end
