classdef Ssb < atomic.Signal
    properties (SetAccess = private)
        messageFreq_Hz (1,1) double {mustBePositive} = 5e3;
        transmissionTotTime (1,1) double {mustBePositive} = 0.004;
    end

    methods
        function this = Ssb(varargin)
            defaults = struct( ...
                'trafficType', "periodic", ...
                'centerFreq_Hz', nan, ...
                'transmissionRate_Hz', 500e3, ...
                'bandwidth_Hz', 50e3, ...
                'txPower_db', 0, ...
                'messageFreq_Hz', 5e3, ...
                'transmissionTotTime', 0.004);

            [opts, ~] = parseOptions(defaults, varargin{:});

            this@atomic.Signal( ...
                'trafficType', opts.trafficType, ...
                'centerFreq_Hz', opts.centerFreq_Hz, ...
                'transmissionRate_Hz', opts.transmissionRate_Hz, ...
                'bandwidth_Hz', opts.bandwidth_Hz, ...
                'txPower_db', opts.txPower_db, ...
                'protocol', report.Protocol.unknown, ...
                'modality', report.Modality.single_carrier, ...
                'modulation', report.Modulation.ssb);

            this.messageFreq_Hz = opts.messageFreq_Hz;
            this.transmissionTotTime = opts.transmissionTotTime;
        end

        function dataIQ = generateTransmission(this)
            nSamples = max(1, round(this.transmissionTotTime * this.transmissionRate_Hz));
            t = (0:nSamples - 1).' / this.transmissionRate_Hz;
            msg = sin(2 * pi * this.messageFreq_Hz * t) + 0.5 * sin(2 * pi * 2 * this.messageFreq_Hz * t);
            dataIQ = hilbert(msg);
        end
    end
end
